http:
  port: ${PORT_GATEWAY}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  chatAPI:
    host: "*"
    paths: ["/api/chat", "/api/chat/*"]
  userAPI:
    host: "*"
    paths: ["/api/user", "/api/user/*"]
  generalAPI:
    host: "*"
    paths: ["/api", "/api/*"]
serviceEndpoints:
  chatService:
    url: "http://localhost:${PORT_CHAT}/"
  generalService:
    url: "http://localhost:${PORT_GENERAL}/"
  userService:
    url: "http://localhost:${PORT_USER}/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  chatPipeline:
    apiEndpoints:
      - chatAPI
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "HEAD,PUT,PATCH,POST,DELETE,GET"
              allowedHeaders:
                [
                  "Content-Type",
                  "Origin",
                  "Authorization",
                  "Access-Control-Allow-Origin",
                  "Accept",
                ]
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - userAPI
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "HEAD,PUT,PATCH,POST,DELETE,GET"
              allowedHeaders:
                [
                  "Content-Type",
                  "Origin",
                  "Authorization",
                  "Access-Control-Allow-Origin",
                  "Accept",
                ]
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  generalPipeline:
    apiEndpoints:
      - generalAPI
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "HEAD,PUT,PATCH,POST,DELETE,GET"
              allowedHeaders:
                [
                  "Content-Type",
                  "Origin",
                  "Authorization",
                  "Access-Control-Allow-Origin",
                  "Accept",
                ]
      - proxy:
          - action:
              serviceEndpoint: generalService
              changeOrigin: true
